import { style } from "@mui/system";
import React from "react";
import styles from "./About.module.css";

const About = () => {
  return (
    <div className={styles.containerAbout}>
      <h2>About</h2>
      <p>
        Butterflies World is a collection of 50 unique NFT’s which were designed
        with vectors and their textures were generated by AI (DreamStudio). This
        drop features one type of butterfly combined with four textured wings.
      </p>
      <p>
        Each piece is a limited edition of 1, and will be minted on the
        blockchain.
      </p>
      <p>
        Butterflies World is an experiment in generative art, and I hope you
        enjoy these pieces as much as I enjoyed making them.
      </p>
      <p>Thank you for your support!</p>
    </div>
  );
};

export default About;

/* 
Butterflies World is a collection of 50 unique NFT’s which were designed with vectors and their textures were generated by AI (DreamStudio). This drop features one type of butterfly combined with four textured wings.

Each piece is a limited edition of 1, and will be minted on the blockchain.

Butterflies World is an experiment in generative art, and I hope you enjoy these pieces as much as I enjoyed making them.

Thank you for your support!
*/
